- Derivan de la clase `Exception`
- Requieren un bloque try/catch
- 